### ISSUE TITLE
Nested Paint3D Repo not cloning, Cannot import name 'utils' from 'ComfyUI-Paint3D-Nodes.Paint3D.paint3d

### ISSUE THREAD

**Issue by picbotvr** [N3rd00d/ComfyUI-Paint3D-Nodes#3]
ImportError: cannot import name 'utils' from 'ComfyUI-Paint3D-Nodes.Paint3D.paint3d' (unknown location)

The folder ComfyUI-Paint3D-Nodes\Paint3D is empty. It doesn't clone when I clone the repository. 

How should I install the ComfyUI-Paint3D-Nodes modules so that the Paint3D module is references properly?

This error occurs on ComfyUI startup when trying to load the ComfyUI-Paint3D-Nodes custom node.

**Comment by Ma0013** [comment]
I have the same issue

**Comment by N3rd00d** [comment]
Due to an internal Git cache issue, the Paint3D source code was not committed correctly. Please fetch the latest commit and try running it again.
