### ISSUE TITLE
downgrading pytorch to install kaolin causes issues with other nodes 

### ISSUE THREAD

**Issue by chrisbward** [N3rd00d/ComfyUI-Paint3D-Nodes#6]
I have other nodes working in Comfy, with `pip install torch==2.3.1 torchvision==0.18.1 torchaudio==2.3.1 --index-url https://download.pytorch.org/whl/cu121`, so unsure how to proceed here!

**Comment by N3rd00d** [comment]
The version of Kaolin is dependent on the versions of Torch, CUDA, and Python. Therefore, you should refer to [https://nvidia-kaolin.s3.us-east-2.amazonaws.com/](https://nvidia-kaolin.s3.us-east-2.amazonaws.com/) and install the Kaolin version that supports your specific Torch version. If it's difficult to change your current development environment, creating and using a new conda environment is also a good option.

**Comment by chrisbward** [comment]
Thanks for the explanation, I'll try to hunt down the version I need and post some feedback here!

**Comment by chrisbward** [comment]
Following that link, I searched for 2.3.1, found the .html and also noticed below this link it listed the kaolin version in the html page, so I updated this also;

```
pip install kaolin==0.16.0 -f https://nvidia-kaolin.s3.us-east-2.amazonaws.com/torch-2.3.1_cu121.html
```

Hopefully that's enough information to allow others to solve the issue depending on their cuda support and torch version

**Comment by chrisbward** [comment]
thank you!
