### ISSUE TITLE
[Question] Do you have any good ideas on how to clearly distinguish the front and back of a model object?

### ISSUE THREAD

**Issue by acts2nine-client** [N3rd00d/ComfyUI-Paint3D-Nodes#7]
As the title suggests, I want to clearly distinguish the front and back of a model object. I want to try using OpenPose, but my model object is not a human figure; it's a piece of clothing.

**Comment by N3rd00d** [comment]
Based on my experience, if the shape does not have a clear distinction between the front and back, it is difficult to create a sampling image as intended.

Therefore, it comes down to luck.

**Comment by acts2nine-client** [comment]
If you have any good ideas, please let me know.
